package Local::TestInput;

use Exporter;
use base Exporter;

our @EXPORT_OK = qw( get_tivo_xml get_tvrage_xml );

my %tvrage_xml = (
    smallville => q{<?xml version="1.0" encoding="UTF-8"?>
<Show>
  <name>Smallville</name>
  <totalseasons>10</totalseasons>
  <Episodelist>
    <Season no="1">
      <episode>
        <epnum>1</epnum>
        <seasonnum>01</seasonnum>
        <prodnum>475165</prodnum>
        <airdate>2001-10-16</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/306040</link>
        <title>Pilot</title>
      </episode>
      <episode>
        <epnum>2</epnum>
        <seasonnum>02</seasonnum>
        <prodnum>227601</prodnum>
        <airdate>2001-10-23</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157361</link>
        <title>Metamorphosis</title>
      </episode>
      <episode>
        <epnum>3</epnum>
        <seasonnum>03</seasonnum>
        <prodnum>227603</prodnum>
        <airdate>2001-10-30</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157362</link>
        <title>Hothead</title>
      </episode>
      <episode>
        <epnum>4</epnum>
        <seasonnum>04</seasonnum>
        <prodnum>227604</prodnum>
        <airdate>2001-11-06</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157363</link>
        <title>X-Ray</title>
      </episode>
      <episode>
        <epnum>5</epnum>
        <seasonnum>05</seasonnum>
        <prodnum>227605</prodnum>
        <airdate>2001-11-13</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157364</link>
        <title>Cool</title>
      </episode>
      <episode>
        <epnum>6</epnum>
        <seasonnum>06</seasonnum>
        <prodnum>227606</prodnum>
        <airdate>2001-11-20</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157365</link>
        <title>Hourglass</title>
      </episode>
      <episode>
        <epnum>7</epnum>
        <seasonnum>07</seasonnum>
        <prodnum>227607</prodnum>
        <airdate>2001-11-27</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157366</link>
        <title>Craving</title>
      </episode>
      <episode>
        <epnum>8</epnum>
        <seasonnum>08</seasonnum>
        <prodnum>227602</prodnum>
        <airdate>2001-12-11</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157367</link>
        <title>Jitters</title>
      </episode>
      <episode>
        <epnum>9</epnum>
        <seasonnum>09</seasonnum>
        <prodnum>227608</prodnum>
        <airdate>2002-01-15</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157368</link>
        <title>Rogue</title>
      </episode>
      <episode>
        <epnum>10</epnum>
        <seasonnum>10</seasonnum>
        <prodnum>227609</prodnum>
        <airdate>2002-01-29</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157369</link>
        <title>Shimmer</title>
      </episode>
      <episode>
        <epnum>11</epnum>
        <seasonnum>11</seasonnum>
        <prodnum>227610</prodnum>
        <airdate>2002-02-05</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157370</link>
        <title>Hug</title>
      </episode>
      <episode>
        <epnum>12</epnum>
        <seasonnum>12</seasonnum>
        <prodnum>227611</prodnum>
        <airdate>2002-02-12</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157371</link>
        <title>Leech</title>
      </episode>
      <episode>
        <epnum>13</epnum>
        <seasonnum>13</seasonnum>
        <prodnum>227612</prodnum>
        <airdate>2002-02-26</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157372</link>
        <title>Kinetic</title>
      </episode>
      <episode>
        <epnum>14</epnum>
        <seasonnum>14</seasonnum>
        <prodnum>227613</prodnum>
        <airdate>2002-03-12</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157373</link>
        <title>Zero</title>
      </episode>
      <episode>
        <epnum>15</epnum>
        <seasonnum>15</seasonnum>
        <prodnum>227614</prodnum>
        <airdate>2002-03-19</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157374</link>
        <title>Nicodemus</title>
      </episode>
      <episode>
        <epnum>16</epnum>
        <seasonnum>16</seasonnum>
        <prodnum>227615</prodnum>
        <airdate>2002-04-16</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157375</link>
        <title>Stray</title>
      </episode>
      <episode>
        <epnum>17</epnum>
        <seasonnum>17</seasonnum>
        <prodnum>227616</prodnum>
        <airdate>2002-04-23</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157376</link>
        <title>Reaper</title>
      </episode>
      <episode>
        <epnum>18</epnum>
        <seasonnum>18</seasonnum>
        <prodnum>227617</prodnum>
        <airdate>2002-04-30</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157377</link>
        <title>Drone</title>
      </episode>
      <episode>
        <epnum>19</epnum>
        <seasonnum>19</seasonnum>
        <prodnum>227618</prodnum>
        <airdate>2002-05-07</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157378</link>
        <title>Crush</title>
      </episode>
      <episode>
        <epnum>20</epnum>
        <seasonnum>20</seasonnum>
        <prodnum>227619</prodnum>
        <airdate>2002-05-14</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157379</link>
        <title>Obscura</title>
      </episode>
      <episode>
        <epnum>21</epnum>
        <seasonnum>21</seasonnum>
        <prodnum>227620</prodnum>
        <airdate>2002-05-21</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157380</link>
        <title>Tempest (1)</title>
      </episode>
    </Season>
    <Season no="2">
      <episode>
        <epnum>22</epnum>
        <seasonnum>01</seasonnum>
        <prodnum>175051</prodnum>
        <airdate>2002-09-24</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157381</link>
        <title>Vortex (2)</title>
      </episode>
      <episode>
        <epnum>23</epnum>
        <seasonnum>02</seasonnum>
        <prodnum>175052</prodnum>
        <airdate>2002-10-01</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157382</link>
        <title>Heat</title>
      </episode>
      <episode>
        <epnum>24</epnum>
        <seasonnum>03</seasonnum>
        <prodnum>175053</prodnum>
        <airdate>2002-10-08</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157383</link>
        <title>Duplicity</title>
      </episode>
      <episode>
        <epnum>25</epnum>
        <seasonnum>04</seasonnum>
        <prodnum>175054</prodnum>
        <airdate>2002-10-15</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157384</link>
        <title>Red</title>
      </episode>
      <episode>
        <epnum>26</epnum>
        <seasonnum>05</seasonnum>
        <prodnum>175055</prodnum>
        <airdate>2002-10-22</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157385</link>
        <title>Nocturne</title>
      </episode>
      <episode>
        <epnum>27</epnum>
        <seasonnum>06</seasonnum>
        <prodnum>227621</prodnum>
        <airdate>2002-10-29</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157386</link>
        <title>Redux</title>
      </episode>
      <episode>
        <epnum>28</epnum>
        <seasonnum>07</seasonnum>
        <prodnum>175056</prodnum>
        <airdate>2002-11-05</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157387</link>
        <title>Lineage</title>
      </episode>
      <episode>
        <epnum>29</epnum>
        <seasonnum>08</seasonnum>
        <prodnum>175057</prodnum>
        <airdate>2002-11-12</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157388</link>
        <title>Ryan</title>
      </episode>
      <episode>
        <epnum>30</epnum>
        <seasonnum>09</seasonnum>
        <prodnum>175058</prodnum>
        <airdate>2002-11-19</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157389</link>
        <title>Dichotic</title>
      </episode>
      <episode>
        <epnum>31</epnum>
        <seasonnum>10</seasonnum>
        <prodnum>175059</prodnum>
        <airdate>2002-11-26</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157390</link>
        <title>Skinwalker</title>
      </episode>
      <episode>
        <epnum>32</epnum>
        <seasonnum>11</seasonnum>
        <prodnum>175060</prodnum>
        <airdate>2003-01-14</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157391</link>
        <title>Visage</title>
      </episode>
      <episode>
        <epnum>33</epnum>
        <seasonnum>12</seasonnum>
        <prodnum>175062</prodnum>
        <airdate>2003-01-21</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157392</link>
        <title>Insurgence</title>
      </episode>
      <episode>
        <epnum>34</epnum>
        <seasonnum>13</seasonnum>
        <prodnum>175061</prodnum>
        <airdate>2003-01-28</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157393</link>
        <title>Suspect</title>
      </episode>
      <episode>
        <epnum>35</epnum>
        <seasonnum>14</seasonnum>
        <prodnum>175063</prodnum>
        <airdate>2003-02-04</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157394</link>
        <title>Rush</title>
      </episode>
      <episode>
        <epnum>36</epnum>
        <seasonnum>15</seasonnum>
        <prodnum>175064</prodnum>
        <airdate>2003-02-11</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157395</link>
        <title>Prodigal</title>
      </episode>
      <episode>
        <epnum>37</epnum>
        <seasonnum>16</seasonnum>
        <prodnum></prodnum>
        <airdate>2003-02-18</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157396</link>
        <title>Fever</title>
      </episode>
      <episode>
        <epnum>38</epnum>
        <seasonnum>17</seasonnum>
        <prodnum></prodnum>
        <airdate>2003-02-25</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157397</link>
        <title>Rosetta</title>
      </episode>
      <episode>
        <epnum>39</epnum>
        <seasonnum>18</seasonnum>
        <prodnum></prodnum>
        <airdate>2003-04-15</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157398</link>
        <title>Visitor</title>
      </episode>
      <episode>
        <epnum>40</epnum>
        <seasonnum>19</seasonnum>
        <prodnum></prodnum>
        <airdate>2003-04-22</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157399</link>
        <title>Precipice</title>
      </episode>
      <episode>
        <epnum>41</epnum>
        <seasonnum>20</seasonnum>
        <prodnum></prodnum>
        <airdate>2003-04-29</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157400</link>
        <title>Witness</title>
      </episode>
      <episode>
        <epnum>42</epnum>
        <seasonnum>21</seasonnum>
        <prodnum></prodnum>
        <airdate>2003-05-06</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157401</link>
        <title>Accelerate</title>
      </episode>
      <episode>
        <epnum>43</epnum>
        <seasonnum>22</seasonnum>
        <prodnum></prodnum>
        <airdate>2003-05-13</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157402</link>
        <title>Calling (1)</title>
      </episode>
      <episode>
        <epnum>44</epnum>
        <seasonnum>23</seasonnum>
        <prodnum></prodnum>
        <airdate>2003-05-20</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157403</link>
        <title>Exodus (2)</title>
      </episode>
    </Season>
    <Season no="3">
      <episode>
        <epnum>45</epnum>
        <seasonnum>01</seasonnum>
        <prodnum>176201</prodnum>
        <airdate>2003-10-01</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157404</link>
        <title>Exile (1)</title>
      </episode>
      <episode>
        <epnum>46</epnum>
        <seasonnum>02</seasonnum>
        <prodnum>176202</prodnum>
        <airdate>2003-10-08</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157405</link>
        <title>Phoenix (2)</title>
      </episode>
      <episode>
        <epnum>47</epnum>
        <seasonnum>03</seasonnum>
        <prodnum>176203</prodnum>
        <airdate>2003-10-15</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157406</link>
        <title>Extinction</title>
      </episode>
      <episode>
        <epnum>48</epnum>
        <seasonnum>04</seasonnum>
        <prodnum>176204</prodnum>
        <airdate>2003-10-22</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157407</link>
        <title>Slumber</title>
      </episode>
      <episode>
        <epnum>49</epnum>
        <seasonnum>05</seasonnum>
        <prodnum>176205</prodnum>
        <airdate>2003-10-29</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157408</link>
        <title>Perry</title>
      </episode>
      <episode>
        <epnum>50</epnum>
        <seasonnum>06</seasonnum>
        <prodnum>176206</prodnum>
        <airdate>2003-11-05</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157409</link>
        <title>Relic</title>
      </episode>
      <episode>
        <epnum>51</epnum>
        <seasonnum>07</seasonnum>
        <prodnum>176207</prodnum>
        <airdate>2003-11-12</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157410</link>
        <title>Magnetic</title>
      </episode>
      <episode>
        <epnum>52</epnum>
        <seasonnum>08</seasonnum>
        <prodnum>176208</prodnum>
        <airdate>2003-11-19</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157411</link>
        <title>Shattered</title>
      </episode>
      <episode>
        <epnum>53</epnum>
        <seasonnum>09</seasonnum>
        <prodnum>176209</prodnum>
        <airdate>2004-01-14</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157412</link>
        <title>Asylum</title>
      </episode>
      <episode>
        <epnum>54</epnum>
        <seasonnum>10</seasonnum>
        <prodnum>176210</prodnum>
        <airdate>2004-01-21</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157413</link>
        <title>Whisper</title>
      </episode>
      <episode>
        <epnum>55</epnum>
        <seasonnum>11</seasonnum>
        <prodnum>176211</prodnum>
        <airdate>2004-01-28</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157414</link>
        <title>Delete</title>
      </episode>
      <episode>
        <epnum>56</epnum>
        <seasonnum>12</seasonnum>
        <prodnum>176212</prodnum>
        <airdate>2004-02-04</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157415</link>
        <title>Hereafter</title>
      </episode>
      <episode>
        <epnum>57</epnum>
        <seasonnum>13</seasonnum>
        <prodnum>176213</prodnum>
        <airdate>2004-02-11</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157416</link>
        <title>Velocity</title>
      </episode>
      <episode>
        <epnum>58</epnum>
        <seasonnum>14</seasonnum>
        <prodnum>176214</prodnum>
        <airdate>2004-02-18</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157417</link>
        <title>Obsession</title>
      </episode>
      <episode>
        <epnum>59</epnum>
        <seasonnum>15</seasonnum>
        <prodnum>176215</prodnum>
        <airdate>2004-02-25</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157418</link>
        <title>Resurrection</title>
      </episode>
      <episode>
        <epnum>60</epnum>
        <seasonnum>16</seasonnum>
        <prodnum>176216</prodnum>
        <airdate>2004-03-03</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157419</link>
        <title>Crisis</title>
      </episode>
      <episode>
        <epnum>61</epnum>
        <seasonnum>17</seasonnum>
        <prodnum>176217</prodnum>
        <airdate>2004-04-14</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157420</link>
        <title>Legacy</title>
      </episode>
      <episode>
        <epnum>62</epnum>
        <seasonnum>18</seasonnum>
        <prodnum>176218</prodnum>
        <airdate>2004-04-21</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157421</link>
        <title>Truth</title>
      </episode>
      <episode>
        <epnum>63</epnum>
        <seasonnum>19</seasonnum>
        <prodnum>176219</prodnum>
        <airdate>2004-04-28</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157422</link>
        <title>Memoria</title>
      </episode>
      <episode>
        <epnum>64</epnum>
        <seasonnum>20</seasonnum>
        <prodnum>176220</prodnum>
        <airdate>2004-05-05</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157423</link>
        <title>Talisman</title>
      </episode>
      <episode>
        <epnum>65</epnum>
        <seasonnum>21</seasonnum>
        <prodnum>176221</prodnum>
        <airdate>2004-05-12</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157424</link>
        <title>Forsaken (1)</title>
      </episode>
      <episode>
        <epnum>66</epnum>
        <seasonnum>22</seasonnum>
        <prodnum>176222</prodnum>
        <airdate>2004-05-19</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157425</link>
        <title>Covenant (2)</title>
      </episode>
    </Season>
    <Season no="4">
      <episode>
        <epnum>67</epnum>
        <seasonnum>01</seasonnum>
        <prodnum>2T5201</prodnum>
        <airdate>2004-09-22</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157426</link>
        <title>Crusade</title>
      </episode>
      <episode>
        <epnum>68</epnum>
        <seasonnum>02</seasonnum>
        <prodnum>2T5202</prodnum>
        <airdate>2004-09-29</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157427</link>
        <title>Gone</title>
      </episode>
      <episode>
        <epnum>69</epnum>
        <seasonnum>03</seasonnum>
        <prodnum>2T5203</prodnum>
        <airdate>2004-10-06</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157428</link>
        <title>Facade</title>
      </episode>
      <episode>
        <epnum>70</epnum>
        <seasonnum>04</seasonnum>
        <prodnum>2T5204</prodnum>
        <airdate>2004-10-13</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157429</link>
        <title>Devoted</title>
      </episode>
      <episode>
        <epnum>71</epnum>
        <seasonnum>05</seasonnum>
        <prodnum>2T5205</prodnum>
        <airdate>2004-10-20</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157430</link>
        <title>Run</title>
      </episode>
      <episode>
        <epnum>72</epnum>
        <seasonnum>06</seasonnum>
        <prodnum>2T5206</prodnum>
        <airdate>2004-10-27</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157431</link>
        <title>Transference</title>
      </episode>
      <episode>
        <epnum>73</epnum>
        <seasonnum>07</seasonnum>
        <prodnum>2T5207</prodnum>
        <airdate>2004-11-03</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157432</link>
        <title>Jinx</title>
      </episode>
      <episode>
        <epnum>74</epnum>
        <seasonnum>08</seasonnum>
        <prodnum>2T5208</prodnum>
        <airdate>2004-11-10</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157433</link>
        <title>Spell</title>
      </episode>
      <episode>
        <epnum>75</epnum>
        <seasonnum>09</seasonnum>
        <prodnum>2T5209</prodnum>
        <airdate>2004-11-17</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157434</link>
        <title>Bound</title>
      </episode>
      <episode>
        <epnum>76</epnum>
        <seasonnum>10</seasonnum>
        <prodnum>2T5210</prodnum>
        <airdate>2004-12-01</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157435</link>
        <title>Scare</title>
      </episode>
      <episode>
        <epnum>77</epnum>
        <seasonnum>11</seasonnum>
        <prodnum>2T5211</prodnum>
        <airdate>2005-01-26</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157436</link>
        <title>Unsafe</title>
      </episode>
      <episode>
        <epnum>78</epnum>
        <seasonnum>12</seasonnum>
        <prodnum>2T5212</prodnum>
        <airdate>2005-02-02</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157437</link>
        <title>Pariah</title>
      </episode>
      <episode>
        <epnum>79</epnum>
        <seasonnum>13</seasonnum>
        <prodnum>2T5213</prodnum>
        <airdate>2005-02-09</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157438</link>
        <title>Recruit</title>
      </episode>
      <episode>
        <epnum>80</epnum>
        <seasonnum>14</seasonnum>
        <prodnum>2T5214</prodnum>
        <airdate>2005-02-16</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157439</link>
        <title>Krypto</title>
      </episode>
      <episode>
        <epnum>81</epnum>
        <seasonnum>15</seasonnum>
        <prodnum>2T5215</prodnum>
        <airdate>2005-02-23</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157440</link>
        <title>Sacred</title>
      </episode>
      <episode>
        <epnum>82</epnum>
        <seasonnum>16</seasonnum>
        <prodnum>2T5216</prodnum>
        <airdate>2005-03-02</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157441</link>
        <title>Lucy</title>
      </episode>
      <episode>
        <epnum>83</epnum>
        <seasonnum>17</seasonnum>
        <prodnum>2T5217</prodnum>
        <airdate>2005-04-13</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157442</link>
        <title>Onyx</title>
      </episode>
      <episode>
        <epnum>84</epnum>
        <seasonnum>18</seasonnum>
        <prodnum>2T5218</prodnum>
        <airdate>2005-04-20</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157443</link>
        <title>Spirit</title>
      </episode>
      <episode>
        <epnum>85</epnum>
        <seasonnum>19</seasonnum>
        <prodnum>2T5219</prodnum>
        <airdate>2005-04-27</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157444</link>
        <title>Blank</title>
      </episode>
      <episode>
        <epnum>86</epnum>
        <seasonnum>20</seasonnum>
        <prodnum>2T5220</prodnum>
        <airdate>2005-05-04</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157445</link>
        <title>Ageless</title>
      </episode>
      <episode>
        <epnum>87</epnum>
        <seasonnum>21</seasonnum>
        <prodnum>2T5221</prodnum>
        <airdate>2005-05-11</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157446</link>
        <title>Forever</title>
      </episode>
      <episode>
        <epnum>88</epnum>
        <seasonnum>22</seasonnum>
        <prodnum>2T5222</prodnum>
        <airdate>2005-05-18</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157447</link>
        <title>Commencement</title>
      </episode>
    </Season>
    <Season no="5">
      <episode>
        <epnum>89</epnum>
        <seasonnum>01</seasonnum>
        <prodnum>2T6401</prodnum>
        <airdate>2005-09-29</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157448</link>
        <title>Arrival</title>
      </episode>
      <episode>
        <epnum>90</epnum>
        <seasonnum>02</seasonnum>
        <prodnum></prodnum>
        <airdate>2005-10-06</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157449</link>
        <title>Mortal</title>
      </episode>
      <episode>
        <epnum>91</epnum>
        <seasonnum>03</seasonnum>
        <prodnum></prodnum>
        <airdate>2005-10-13</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157450</link>
        <title>Hidden</title>
      </episode>
      <episode>
        <epnum>92</epnum>
        <seasonnum>04</seasonnum>
        <prodnum></prodnum>
        <airdate>2005-10-20</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157451</link>
        <title>Aqua</title>
      </episode>
      <episode>
        <epnum>93</epnum>
        <seasonnum>05</seasonnum>
        <prodnum></prodnum>
        <airdate>2005-10-27</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157452</link>
        <title>Thirst</title>
      </episode>
      <episode>
        <epnum>94</epnum>
        <seasonnum>06</seasonnum>
        <prodnum></prodnum>
        <airdate>2005-11-03</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/157453</link>
        <title>Exposed</title>
      </episode>
      <episode>
        <epnum>95</epnum>
        <seasonnum>07</seasonnum>
        <prodnum></prodnum>
        <airdate>2005-11-10</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/304528</link>
        <title>Splinter</title>
      </episode>
      <episode>
        <epnum>96</epnum>
        <seasonnum>08</seasonnum>
        <prodnum></prodnum>
        <airdate>2005-11-17</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/304529</link>
        <title>Solitude</title>
      </episode>
      <episode>
        <epnum>97</epnum>
        <seasonnum>09</seasonnum>
        <prodnum></prodnum>
        <airdate>2005-12-08</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/304530</link>
        <title>Lexmas</title>
      </episode>
      <episode>
        <epnum>98</epnum>
        <seasonnum>10</seasonnum>
        <prodnum></prodnum>
        <airdate>2006-01-12</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/308482</link>
        <title>Fanatic</title>
      </episode>
      <episode>
        <epnum>99</epnum>
        <seasonnum>11</seasonnum>
        <prodnum>2T6411</prodnum>
        <airdate>2006-01-19</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/309362</link>
        <title>Lockdown</title>
      </episode>
      <episode>
        <epnum>100</epnum>
        <seasonnum>12</seasonnum>
        <prodnum>2T6412</prodnum>
        <airdate>2006-01-26</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/310396</link>
        <title>Reckoning</title>
      </episode>
      <episode>
        <epnum>101</epnum>
        <seasonnum>13</seasonnum>
        <prodnum>2T6413</prodnum>
        <airdate>2006-02-02</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/310397</link>
        <title>Vengeance</title>
      </episode>
      <episode>
        <epnum>102</epnum>
        <seasonnum>14</seasonnum>
        <prodnum>2T6414</prodnum>
        <airdate>2006-02-09</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/310398</link>
        <title>Tomb</title>
      </episode>
      <episode>
        <epnum>103</epnum>
        <seasonnum>15</seasonnum>
        <prodnum>2T6415</prodnum>
        <airdate>2006-02-16</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/310399</link>
        <title>Cyborg</title>
      </episode>
      <episode>
        <epnum>104</epnum>
        <seasonnum>16</seasonnum>
        <prodnum>2T6416</prodnum>
        <airdate>2006-03-30</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/313785</link>
        <title>Hypnotic</title>
      </episode>
      <episode>
        <epnum>105</epnum>
        <seasonnum>17</seasonnum>
        <prodnum>2T6417</prodnum>
        <airdate>2006-04-06</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/319888</link>
        <title>Void</title>
      </episode>
      <episode>
        <epnum>106</epnum>
        <seasonnum>18</seasonnum>
        <prodnum>2T6418</prodnum>
        <airdate>2006-04-13</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/319889</link>
        <title>Fragile</title>
      </episode>
      <episode>
        <epnum>107</epnum>
        <seasonnum>19</seasonnum>
        <prodnum>2T6419</prodnum>
        <airdate>2006-04-20</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/326571</link>
        <title>Mercy</title>
      </episode>
      <episode>
        <epnum>108</epnum>
        <seasonnum>20</seasonnum>
        <prodnum>2T6420</prodnum>
        <airdate>2006-04-27</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/326572</link>
        <title>Fade</title>
      </episode>
      <episode>
        <epnum>109</epnum>
        <seasonnum>21</seasonnum>
        <prodnum>2T6421</prodnum>
        <airdate>2006-05-04</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/326573</link>
        <title>Oracle</title>
      </episode>
      <episode>
        <epnum>110</epnum>
        <seasonnum>22</seasonnum>
        <prodnum>2T6422</prodnum>
        <airdate>2006-05-11</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/326574</link>
        <title>Vessel</title>
      </episode>
    </Season>
    <Season no="6">
      <episode>
        <epnum>111</epnum>
        <seasonnum>01</seasonnum>
        <prodnum>2T6423</prodnum>
        <airdate>2006-09-28</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/400964</link>
        <title>Zod</title>
      </episode>
      <episode>
        <epnum>112</epnum>
        <seasonnum>02</seasonnum>
        <prodnum>2T6424</prodnum>
        <airdate>2006-10-05</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/411725</link>
        <title>Sneeze</title>
      </episode>
      <episode>
        <epnum>113</epnum>
        <seasonnum>03</seasonnum>
        <prodnum>2T6424</prodnum>
        <airdate>2006-10-12</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/411726</link>
        <title>Wither</title>
      </episode>
      <episode>
        <epnum>114</epnum>
        <seasonnum>04</seasonnum>
        <prodnum>2T7704</prodnum>
        <airdate>2006-10-19</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/416831</link>
        <title>Arrow</title>
      </episode>
      <episode>
        <epnum>115</epnum>
        <seasonnum>05</seasonnum>
        <prodnum>2T7705</prodnum>
        <airdate>2006-10-26</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/436607</link>
        <title>Reunion</title>
      </episode>
      <episode>
        <epnum>116</epnum>
        <seasonnum>06</seasonnum>
        <prodnum>2T7706</prodnum>
        <airdate>2006-11-02</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/444868</link>
        <title>Fallout</title>
      </episode>
      <episode>
        <epnum>117</epnum>
        <seasonnum>07</seasonnum>
        <prodnum>2T7708</prodnum>
        <airdate>2006-11-09</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/444869</link>
        <title>Rage</title>
      </episode>
      <episode>
        <epnum>118</epnum>
        <seasonnum>08</seasonnum>
        <prodnum>2T7709</prodnum>
        <airdate>2006-11-16</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/450642</link>
        <title>Static</title>
      </episode>
      <episode>
        <epnum>119</epnum>
        <seasonnum>09</seasonnum>
        <prodnum>2T7707</prodnum>
        <airdate>2006-12-07</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/419621</link>
        <title>Subterranean</title>
      </episode>
      <episode>
        <epnum>120</epnum>
        <seasonnum>10</seasonnum>
        <prodnum>2T7710</prodnum>
        <airdate>2007-01-11</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/450643</link>
        <title>Hydro</title>
      </episode>
      <episode>
        <epnum>121</epnum>
        <seasonnum>11</seasonnum>
        <prodnum>2T7711</prodnum>
        <airdate>2007-01-18</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/450644</link>
        <title>Justice</title>
      </episode>
      <episode>
        <epnum>122</epnum>
        <seasonnum>12</seasonnum>
        <prodnum>2T7712</prodnum>
        <airdate>2007-01-25</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/476309</link>
        <title>Labyrinth</title>
      </episode>
      <episode>
        <epnum>123</epnum>
        <seasonnum>13</seasonnum>
        <prodnum>2T7713</prodnum>
        <airdate>2007-02-01</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/476310</link>
        <title>Crimson</title>
      </episode>
      <episode>
        <epnum>124</epnum>
        <seasonnum>14</seasonnum>
        <prodnum>2T7714</prodnum>
        <airdate>2007-02-08</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/490246</link>
        <title>Trespass</title>
      </episode>
      <episode>
        <epnum>125</epnum>
        <seasonnum>15</seasonnum>
        <prodnum>2T7715</prodnum>
        <airdate>2007-02-15</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/490247</link>
        <title>Freak</title>
      </episode>
      <episode>
        <epnum>126</epnum>
        <seasonnum>16</seasonnum>
        <prodnum>2T7716</prodnum>
        <airdate>2007-03-15</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/508104</link>
        <title>Promise</title>
      </episode>
      <episode>
        <epnum>127</epnum>
        <seasonnum>17</seasonnum>
        <prodnum>2T7717</prodnum>
        <airdate>2007-03-22</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/508105</link>
        <title>Combat</title>
      </episode>
      <episode>
        <epnum>128</epnum>
        <seasonnum>18</seasonnum>
        <prodnum>2T7718</prodnum>
        <airdate>2007-04-19</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/517715</link>
        <title>Progeny</title>
      </episode>
      <episode>
        <epnum>129</epnum>
        <seasonnum>19</seasonnum>
        <prodnum>2T7719</prodnum>
        <airdate>2007-04-26</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/521508</link>
        <title>Nemesis</title>
      </episode>
      <episode>
        <epnum>130</epnum>
        <seasonnum>20</seasonnum>
        <prodnum>2T7720</prodnum>
        <airdate>2007-05-03</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/521816</link>
        <title>Noir</title>
      </episode>
      <episode>
        <epnum>131</epnum>
        <seasonnum>21</seasonnum>
        <prodnum>2T7721</prodnum>
        <airdate>2007-05-10</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/521817</link>
        <title>Prototype</title>
      </episode>
      <episode>
        <epnum>132</epnum>
        <seasonnum>22</seasonnum>
        <prodnum>2T7722</prodnum>
        <airdate>2007-05-17</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/526304</link>
        <title>Phantom</title>
      </episode>
    </Season>
    <Season no="7">
      <episode>
        <epnum>133</epnum>
        <seasonnum>01</seasonnum>
        <prodnum>3T6301</prodnum>
        <airdate>2007-09-27</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/576581</link>
        <title>Bizarro</title>
      </episode>
      <episode>
        <epnum>134</epnum>
        <seasonnum>02</seasonnum>
        <prodnum>3T6302</prodnum>
        <airdate>2007-10-04</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/583102</link>
        <title>Kara</title>
      </episode>
      <episode>
        <epnum>135</epnum>
        <seasonnum>03</seasonnum>
        <prodnum>3T6303</prodnum>
        <airdate>2007-10-11</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/583103</link>
        <title>Fierce</title>
      </episode>
      <episode>
        <epnum>136</epnum>
        <seasonnum>04</seasonnum>
        <prodnum>3T6304</prodnum>
        <airdate>2007-10-18</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/586264</link>
        <title>Cure</title>
      </episode>
      <episode>
        <epnum>137</epnum>
        <seasonnum>05</seasonnum>
        <prodnum>3T6306</prodnum>
        <airdate>2007-10-25</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/592094</link>
        <title>Action</title>
      </episode>
      <episode>
        <epnum>138</epnum>
        <seasonnum>06</seasonnum>
        <prodnum>3T6305</prodnum>
        <airdate>2007-11-01</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/592095</link>
        <title>Lara</title>
      </episode>
      <episode>
        <epnum>139</epnum>
        <seasonnum>07</seasonnum>
        <prodnum>3T6307</prodnum>
        <airdate>2007-11-08</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/606065</link>
        <title>Wrath</title>
      </episode>
      <episode>
        <epnum>140</epnum>
        <seasonnum>08</seasonnum>
        <prodnum>3T6308</prodnum>
        <airdate>2007-11-15</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/606066</link>
        <title>Blue</title>
      </episode>
      <episode>
        <epnum>141</epnum>
        <seasonnum>09</seasonnum>
        <prodnum>3T6309</prodnum>
        <airdate>2007-12-13</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/606067</link>
        <title>Gemini</title>
      </episode>
      <episode>
        <epnum>142</epnum>
        <seasonnum>10</seasonnum>
        <prodnum>3T6310</prodnum>
        <airdate>2008-01-31</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/620873</link>
        <title>Persona</title>
      </episode>
      <episode>
        <epnum>143</epnum>
        <seasonnum>11</seasonnum>
        <prodnum>3T6311</prodnum>
        <airdate>2008-02-07</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/620874</link>
        <title>Siren</title>
      </episode>
      <episode>
        <epnum>144</epnum>
        <seasonnum>12</seasonnum>
        <prodnum>3T6312</prodnum>
        <airdate>2008-02-14</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/627546</link>
        <title>Fracture</title>
      </episode>
      <episode>
        <epnum>145</epnum>
        <seasonnum>13</seasonnum>
        <prodnum>3T6313</prodnum>
        <airdate>2008-03-13</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/627547</link>
        <title>Hero</title>
      </episode>
      <episode>
        <epnum>146</epnum>
        <seasonnum>14</seasonnum>
        <prodnum>3T6314</prodnum>
        <airdate>2008-03-20</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/627548</link>
        <title>Traveler</title>
      </episode>
      <episode>
        <epnum>147</epnum>
        <seasonnum>15</seasonnum>
        <prodnum>3T6315</prodnum>
        <airdate>2008-03-27</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/627545</link>
        <title>Veritas</title>
      </episode>
      <episode>
        <epnum>148</epnum>
        <seasonnum>16</seasonnum>
        <prodnum>3T6316</prodnum>
        <airdate>2008-04-17</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/646966</link>
        <title>Descent</title>
      </episode>
      <episode>
        <epnum>149</epnum>
        <seasonnum>17</seasonnum>
        <prodnum>3T6317</prodnum>
        <airdate>2008-04-24</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/646967</link>
        <title>Sleeper</title>
      </episode>
      <episode>
        <epnum>150</epnum>
        <seasonnum>18</seasonnum>
        <prodnum>3T6318</prodnum>
        <airdate>2008-05-01</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/646968</link>
        <title>Apocalypse</title>
      </episode>
      <episode>
        <epnum>151</epnum>
        <seasonnum>19</seasonnum>
        <prodnum>3T6319</prodnum>
        <airdate>2008-05-08</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/646969</link>
        <title>Quest</title>
      </episode>
      <episode>
        <epnum>152</epnum>
        <seasonnum>20</seasonnum>
        <prodnum>3T6320</prodnum>
        <airdate>2008-05-15</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/646970</link>
        <title>Arctic</title>
      </episode>
    </Season>
    <Season no="8">
      <episode>
        <epnum>153</epnum>
        <seasonnum>01</seasonnum>
        <prodnum>3T7451</prodnum>
        <airdate>2008-09-18</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/682931</link>
        <title>Odyssey</title>
      </episode>
      <episode>
        <epnum>154</epnum>
        <seasonnum>02</seasonnum>
        <prodnum>3T7452</prodnum>
        <airdate>2008-09-25</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/682932</link>
        <title>Plastique</title>
      </episode>
      <episode>
        <epnum>155</epnum>
        <seasonnum>03</seasonnum>
        <prodnum>3T7453</prodnum>
        <airdate>2008-10-02</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/686676</link>
        <title>Toxic</title>
      </episode>
      <episode>
        <epnum>156</epnum>
        <seasonnum>04</seasonnum>
        <prodnum>3T7454</prodnum>
        <airdate>2008-10-09</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/691933</link>
        <title>Instinct</title>
      </episode>
      <episode>
        <epnum>157</epnum>
        <seasonnum>05</seasonnum>
        <prodnum>3T7455</prodnum>
        <airdate>2008-10-16</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/691934</link>
        <title>Committed</title>
      </episode>
      <episode>
        <epnum>158</epnum>
        <seasonnum>06</seasonnum>
        <prodnum>3T7456</prodnum>
        <airdate>2008-10-23</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/697845</link>
        <title>Prey</title>
      </episode>
      <episode>
        <epnum>159</epnum>
        <seasonnum>07</seasonnum>
        <prodnum>3T7457</prodnum>
        <airdate>2008-10-30</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/704540</link>
        <title>Identity</title>
      </episode>
      <episode>
        <epnum>160</epnum>
        <seasonnum>08</seasonnum>
        <prodnum>3T7459</prodnum>
        <airdate>2008-11-06</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/704541</link>
        <title>Bloodline</title>
      </episode>
      <episode>
        <epnum>161</epnum>
        <seasonnum>09</seasonnum>
        <prodnum>3T7458</prodnum>
        <airdate>2008-11-13</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/706489</link>
        <title>Abyss</title>
      </episode>
      <episode>
        <epnum>162</epnum>
        <seasonnum>10</seasonnum>
        <prodnum>3T7460</prodnum>
        <airdate>2008-11-20</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/706490</link>
        <title>Bride</title>
      </episode>
      <episode>
        <epnum>163</epnum>
        <seasonnum>11</seasonnum>
        <prodnum>3T7461</prodnum>
        <airdate>2009-01-15</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/697846</link>
        <title>Legion</title>
      </episode>
      <episode>
        <epnum>164</epnum>
        <seasonnum>12</seasonnum>
        <prodnum>3T7462</prodnum>
        <airdate>2009-01-22</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/725588</link>
        <title>Bulletproof</title>
      </episode>
      <episode>
        <epnum>165</epnum>
        <seasonnum>13</seasonnum>
        <prodnum>3T7463</prodnum>
        <airdate>2009-01-29</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/743070</link>
        <title>Power</title>
      </episode>
      <episode>
        <epnum>166</epnum>
        <seasonnum>14</seasonnum>
        <prodnum>3T7464</prodnum>
        <airdate>2009-02-05</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/744841</link>
        <title>Requiem</title>
      </episode>
      <episode>
        <epnum>167</epnum>
        <seasonnum>15</seasonnum>
        <prodnum>3T7465</prodnum>
        <airdate>2009-03-12</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/744843</link>
        <title>Infamous</title>
      </episode>
      <episode>
        <epnum>168</epnum>
        <seasonnum>16</seasonnum>
        <prodnum>3T7466</prodnum>
        <airdate>2009-03-19</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/768870</link>
        <title>Turbulence</title>
      </episode>
      <episode>
        <epnum>169</epnum>
        <seasonnum>17</seasonnum>
        <prodnum>3T7467</prodnum>
        <airdate>2009-03-26</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/772709</link>
        <title>Hex</title>
      </episode>
      <episode>
        <epnum>170</epnum>
        <seasonnum>18</seasonnum>
        <prodnum>3T7468</prodnum>
        <airdate>2009-04-02</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/778350</link>
        <title>Eternal</title>
      </episode>
      <episode>
        <epnum>171</epnum>
        <seasonnum>19</seasonnum>
        <prodnum>3T7469</prodnum>
        <airdate>2009-04-23</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/778352</link>
        <title>Stiletto</title>
      </episode>
      <episode>
        <epnum>172</epnum>
        <seasonnum>20</seasonnum>
        <prodnum>3T7470</prodnum>
        <airdate>2009-04-30</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/785695</link>
        <title>Beast</title>
      </episode>
      <episode>
        <epnum>173</epnum>
        <seasonnum>21</seasonnum>
        <prodnum>3T7471</prodnum>
        <airdate>2009-05-07</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/785696</link>
        <title>Injustice</title>
      </episode>
      <episode>
        <epnum>174</epnum>
        <seasonnum>22</seasonnum>
        <prodnum>3T7472</prodnum>
        <airdate>2009-05-14</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/785697</link>
        <title>Doomsday</title>
      </episode>
    </Season>
    <Season no="9">
      <episode>
        <epnum>175</epnum>
        <seasonnum>01</seasonnum>
        <prodnum>3X5251</prodnum>
        <airdate>2009-09-25</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064825437</link>
        <title>Savior</title>
      </episode>
      <episode>
        <epnum>176</epnum>
        <seasonnum>02</seasonnum>
        <prodnum>3X5252</prodnum>
        <airdate>2009-10-02</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064829854</link>
        <title>Metallo</title>
      </episode>
      <episode>
        <epnum>177</epnum>
        <seasonnum>03</seasonnum>
        <prodnum>3X5253</prodnum>
        <airdate>2009-10-09</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064837958</link>
        <title>Rabid</title>
      </episode>
      <episode>
        <epnum>178</epnum>
        <seasonnum>04</seasonnum>
        <prodnum>3X5254</prodnum>
        <airdate>2009-10-16</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064838838</link>
        <title>Echo</title>
      </episode>
      <episode>
        <epnum>179</epnum>
        <seasonnum>05</seasonnum>
        <prodnum>3X5256</prodnum>
        <airdate>2009-10-23</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064842226</link>
        <title>Roulette</title>
      </episode>
      <episode>
        <epnum>180</epnum>
        <seasonnum>06</seasonnum>
        <prodnum>3X5257</prodnum>
        <airdate>2009-10-30</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064842227</link>
        <title>Crossfire</title>
      </episode>
      <episode>
        <epnum>181</epnum>
        <seasonnum>07</seasonnum>
        <prodnum>3X5258</prodnum>
        <airdate>2009-11-06</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064842228</link>
        <title>Kandor</title>
      </episode>
      <episode>
        <epnum>182</epnum>
        <seasonnum>08</seasonnum>
        <prodnum>3X5255</prodnum>
        <airdate>2009-11-13</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064840391</link>
        <title>Idol</title>
      </episode>
      <episode>
        <epnum>183</epnum>
        <seasonnum>09</seasonnum>
        <prodnum>3X5259</prodnum>
        <airdate>2009-11-20</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064846320</link>
        <title>Pandora</title>
      </episode>
      <episode>
        <epnum>184</epnum>
        <seasonnum>10</seasonnum>
        <prodnum>3X5260</prodnum>
        <airdate>2010-01-29</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064852105</link>
        <title>Disciple</title>
      </episode>
      <episode>
        <epnum>185</epnum>
        <seasonnum>11</seasonnum>
        <prodnum></prodnum>
        <airdate>2010-02-05</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064864696</link>
        <title>Absolute Justice</title>
      </episode>
      <episode>
        <epnum>186</epnum>
        <seasonnum>12</seasonnum>
        <prodnum>3X5263</prodnum>
        <airdate>2010-02-12</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064875553</link>
        <title>Warrior</title>
      </episode>
      <episode>
        <epnum>187</epnum>
        <seasonnum>13</seasonnum>
        <prodnum>3X5266</prodnum>
        <airdate>2010-02-19</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064864697</link>
        <title>Persuasion</title>
      </episode>
      <episode>
        <epnum>188</epnum>
        <seasonnum>14</seasonnum>
        <prodnum>3X5264</prodnum>
        <airdate>2010-02-26</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064875490</link>
        <title>Conspiracy</title>
      </episode>
      <episode>
        <epnum>189</epnum>
        <seasonnum>15</seasonnum>
        <prodnum>3X5266</prodnum>
        <airdate>2010-04-02</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064902226</link>
        <title>Escape</title>
      </episode>
      <episode>
        <epnum>190</epnum>
        <seasonnum>16</seasonnum>
        <prodnum>3X5267</prodnum>
        <airdate>2010-04-09</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064902225</link>
        <title>Checkmate</title>
      </episode>
      <episode>
        <epnum>191</epnum>
        <seasonnum>17</seasonnum>
        <prodnum>3X5268</prodnum>
        <airdate>2010-04-16</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064902227</link>
        <title>Upgrade</title>
      </episode>
      <episode>
        <epnum>192</epnum>
        <seasonnum>18</seasonnum>
        <prodnum>3X5269</prodnum>
        <airdate>2010-04-23</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064904711</link>
        <title>Charade</title>
      </episode>
      <episode>
        <epnum>193</epnum>
        <seasonnum>19</seasonnum>
        <prodnum>3X5270</prodnum>
        <airdate>2010-04-30</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064904712</link>
        <title>Sacrifice</title>
      </episode>
      <episode>
        <epnum>194</epnum>
        <seasonnum>20</seasonnum>
        <prodnum>3X5271</prodnum>
        <airdate>2010-05-07</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064906221</link>
        <title>Hostage</title>
      </episode>
      <episode>
        <epnum>195</epnum>
        <seasonnum>21</seasonnum>
        <prodnum>3X5272</prodnum>
        <airdate>2010-05-14</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064906222</link>
        <title>Salvation</title>
      </episode>
    </Season>
    <Season no="10">
      <episode>
        <epnum>196</epnum>
        <seasonnum>01</seasonnum>
        <prodnum>3X6001</prodnum>
        <airdate>2010-09-24</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064944878</link>
        <title>Lazarus</title>
      </episode>
      <episode>
        <epnum>197</epnum>
        <seasonnum>02</seasonnum>
        <prodnum>3X6002</prodnum>
        <airdate>2010-10-01</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064956980</link>
        <title>Shield</title>
      </episode>
      <episode>
        <epnum>198</epnum>
        <seasonnum>03</seasonnum>
        <prodnum>3X6003</prodnum>
        <airdate>2010-10-08</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064966950</link>
        <title>Supergirl</title>
      </episode>
      <episode>
        <epnum>199</epnum>
        <seasonnum>04</seasonnum>
        <prodnum>3X6004</prodnum>
        <airdate>2010-10-15</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064966951</link>
        <title>Homecoming</title>
      </episode>
      <episode>
        <epnum>200</epnum>
        <seasonnum>05</seasonnum>
        <prodnum>3X6005</prodnum>
        <airdate>2010-10-22</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064966952</link>
        <title>Isis</title>
      </episode>
      <episode>
        <epnum>201</epnum>
        <seasonnum>06</seasonnum>
        <prodnum>3X6006</prodnum>
        <airdate>2010-10-29</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064966953</link>
        <title>Harvest</title>
      </episode>
      <episode>
        <epnum>202</epnum>
        <seasonnum>07</seasonnum>
        <prodnum>3X6007</prodnum>
        <airdate>2010-11-05</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064978459</link>
        <title>Ambush</title>
      </episode>
      <episode>
        <epnum>203</epnum>
        <seasonnum>08</seasonnum>
        <prodnum>3X6008</prodnum>
        <airdate>2010-11-12</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064978796</link>
        <title>Abandoned</title>
      </episode>
      <episode>
        <epnum>204</epnum>
        <seasonnum>09</seasonnum>
        <prodnum>3X6009</prodnum>
        <airdate>2010-11-19</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064978797</link>
        <title>Patriot</title>
      </episode>
      <episode>
        <epnum>205</epnum>
        <seasonnum>10</seasonnum>
        <prodnum>3X6010</prodnum>
        <airdate>2010-12-03</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064982816</link>
        <title>Luthor</title>
      </episode>
      <episode>
        <epnum>206</epnum>
        <seasonnum>11</seasonnum>
        <prodnum>3X6011</prodnum>
        <airdate>2010-12-10</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064982817</link>
        <title>Icarus</title>
      </episode>
      <episode>
        <epnum>207</epnum>
        <seasonnum>12</seasonnum>
        <prodnum>3X6012</prodnum>
        <airdate>2011-02-04</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064995414</link>
        <title>Collateral</title>
      </episode>
      <episode>
        <epnum>208</epnum>
        <seasonnum>13</seasonnum>
        <prodnum>3X6013</prodnum>
        <airdate>2011-02-11</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1064995415</link>
        <title>Beacon</title>
      </episode>
      <episode>
        <epnum>209</epnum>
        <seasonnum>14</seasonnum>
        <prodnum>3X6014</prodnum>
        <airdate>2011-02-18</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1065000694</link>
        <title>Masquerade</title>
      </episode>
      <episode>
        <epnum>210</epnum>
        <seasonnum>15</seasonnum>
        <prodnum>3X6015</prodnum>
        <airdate>2011-02-25</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1065000695</link>
        <title>Fortune</title>
      </episode>
      <episode>
        <epnum>211</epnum>
        <seasonnum>16</seasonnum>
        <prodnum>3X6016</prodnum>
        <airdate>2011-03-04</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1065000696</link>
        <title>Scion</title>
      </episode>
      <episode>
        <epnum>212</epnum>
        <seasonnum>17</seasonnum>
        <prodnum>3X6018</prodnum>
        <airdate>2011-04-15</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1065012836</link>
        <title>Kent</title>
      </episode>
      <episode>
        <epnum>213</epnum>
        <seasonnum>18</seasonnum>
        <prodnum>3X6019</prodnum>
        <airdate>2011-04-22</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1065012835</link>
        <title>Booster</title>
      </episode>
      <episode>
        <epnum>214</epnum>
        <seasonnum>19</seasonnum>
        <prodnum>3X6019</prodnum>
        <airdate>2011-04-29</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1065015830</link>
        <title>Dominion</title>
      </episode>
      <episode>
        <epnum>215</epnum>
        <seasonnum>20</seasonnum>
        <prodnum>3X6020</prodnum>
        <airdate>2011-05-06</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1065015831</link>
        <title>Prophecy</title>
      </episode>
      <episode>
        <epnum>216</epnum>
        <seasonnum>21</seasonnum>
        <prodnum></prodnum>
        <airdate>2011-05-13</airdate>
        <link>http://www.tvrage.com/Smallville/episodes/1065015832</link>
        <title>Finale</title>
      </episode>
    </Season>
  </Episodelist>
</Show>
},
);

my %tivo_xml = (
    smallville => {
        vortex => q{<?xml version="1.0" encoding="utf-8"?>
<TvBusMarshalledStruct:TvBusEnvelope xmlns:TvBusDateTime="http://tivo.com/developer/xml/idl/TvBusDateTime" xmlns:TvBusDuration="http://tivo.com/developer/xml/idl/TvBusDuration" xmlns:TvBusMarshalledStruct="http://tivo.com/developer/xml/idl/TvBusMarshalledStruct" xmlns:TvDbBitstreamFormat="http://tivo.com/developer/xml/idl/TvDbBitstreamFormat" xmlns:TvDbColorCode="http://tivo.com/developer/xml/idl/TvDbColorCode" xmlns:TvDbRecordQuality="http://tivo.com/developer/xml/idl/TvDbRecordQuality" xmlns:TvDbShowType="http://tivo.com/developer/xml/idl/TvDbShowType" xmlns:TvDbShowingBit="http://tivo.com/developer/xml/idl/TvDbShowingBit" xmlns:TvDbTvRating="http://tivo.com/developer/xml/idl/TvDbTvRating" xmlns:TvPgdChannel="http://tivo.com/developer/xml/idl/TvPgdChannel" xmlns:TvPgdProgram="http://tivo.com/developer/xml/idl/TvPgdProgram" xmlns:TvPgdRecording="http://tivo.com/developer/xml/idl/TvPgdRecording" xmlns:TvPgdSeries="http://tivo.com/developer/xml/idl/TvPgdSeries" xmlns:TvPgdShowing="http://tivo.com/developer/xml/idl/TvPgdShowing" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="http://tivo.com/developer/xml/idl/TvBusMarshalledStruct TvBusMarshalledStruct.xsd http://tivo.com/developer/xml/idl/TvPgdRecording TvPgdRecording.xsd http://tivo.com/developer/xml/idl/TvBusDuration TvBusDuration.xsd http://tivo.com/developer/xml/idl/TvPgdShowing TvPgdShowing.xsd http://tivo.com/developer/xml/idl/TvDbShowingBit TvDbShowingBit.xsd http://tivo.com/developer/xml/idl/TvBusDateTime TvBusDateTime.xsd http://tivo.com/developer/xml/idl/TvPgdProgram TvPgdProgram.xsd http://tivo.com/developer/xml/idl/TvDbColorCode TvDbColorCode.xsd http://tivo.com/developer/xml/idl/TvPgdSeries TvPgdSeries.xsd http://tivo.com/developer/xml/idl/TvDbShowType TvDbShowType.xsd http://tivo.com/developer/xml/idl/TvDbTvRating TvDbTvRating.xsd http://tivo.com/developer/xml/idl/TvDbRecordQuality TvDbRecordQuality.xsd http://tivo.com/developer/xml/idl/TvPgdChannel TvPgdChannel.xsd http://tivo.com/developer/xml/idl/TvDbBitstreamFormat TvDbBitstreamFormat.xsd" xs:type="TvPgdRecording:TvPgdRecording">
  <recordedDuration>PT59M52S</recordedDuration>
  <vActualShowing>
    <element>
      <showingBits value="393763"/>
      <time>2014-01-16T14:00:00Z</time>
      <duration>PT1H</duration>
      <program>
        <vActor>
          <element>Welling|Tom</element>
          <element>Rosenbaum|Michael</element>
          <element>Kreuk|Kristin</element>
          <element>Jones III|Sam</element>
          <element>Mack|Allison</element>
          <element>Schneider|John</element>
          <element>O'Toole|Annette</element>
        </vActor>
        <vAdvisory/>
        <vChoreographer/>
        <colorCode value="4">COLOR</colorCode>
        <description>A wild storm buries alive Clark's father and a reporter (Tom O'Brien) who has uncovered Clark's secret. Copyright Tribune Media Services, Inc.</description>
        <vDirector>
          <element>Beeman|Greg</element>
        </vDirector>
        <episodeNumber>22</episodeNumber>
        <episodeTitle>Vortex</episodeTitle>
        <vExecProducer>
          <element>Gough|Alfred</element>
          <element>Millar|Miles</element>
        </vExecProducer>
        <vProgramGenre>
          <element>Action Adventure</element>
          <element>Drama</element>
          <element>Fantasy</element>
        </vProgramGenre>
        <vGuestStar>
          <element>O'Brien|Tom</element>
          <element>Glover|John</element>
        </vGuestStar>
        <vHost/>
        <isEpisode>true</isEpisode>
        <originalAirDate>2002-09-24T00:00:00Z</originalAirDate>
        <vProducer/>
        <series>
          <isEpisodic>true</isEpisodic>
          <vSeriesGenre>
            <element>Action Adventure</element>
            <element>Drama</element>
            <element>Fantasy</element>
            <element>Drama</element>
            <element>Action Adventure</element>
            <element>Sci-Fi and Fantasy</element>
          </vSeriesGenre>
          <seriesTitle>Smallville</seriesTitle>
        </series>
        <showType value="5">SERIES</showType>
        <title>Smallville</title>
        <vWriter>
          <element>Gough|Alfred</element>
          <element>Millar|Miles</element>
          <element>Levens|Philip</element>
        </vWriter>
      </program>
      <tvRating value="4">PG</tvRating>
    </element>
  </vActualShowing>
  <vBookmark/>
  <recordingQuality value="75">HIGH</recordingQuality>
  <showing>
    <showingBits value="393763"/>
    <time>2014-01-16T14:00:00Z</time>
    <duration>PT1H</duration>
    <program>
      <vActor>
        <element>Welling|Tom</element>
        <element>Rosenbaum|Michael</element>
        <element>Kreuk|Kristin</element>
        <element>Jones III|Sam</element>
        <element>Mack|Allison</element>
        <element>Schneider|John</element>
        <element>O'Toole|Annette</element>
      </vActor>
      <vAdvisory/>
      <vChoreographer/>
      <colorCode value="4">COLOR</colorCode>
      <description>A wild storm buries alive Clark's father and a reporter (Tom O'Brien) who has uncovered Clark's secret. Copyright Tribune Media Services, Inc.</description>
      <vDirector>
        <element>Beeman|Greg</element>
      </vDirector>
      <episodeNumber>22</episodeNumber>
      <episodeTitle>Vortex</episodeTitle>
      <vExecProducer>
        <element>Gough|Alfred</element>
        <element>Millar|Miles</element>
      </vExecProducer>
      <vProgramGenre>
        <element>Action Adventure</element>
        <element>Drama</element>
        <element>Fantasy</element>
      </vProgramGenre>
      <vGuestStar>
        <element>O'Brien|Tom</element>
        <element>Glover|John</element>
      </vGuestStar>
      <vHost/>
      <isEpisode>true</isEpisode>
      <originalAirDate>2002-09-24T00:00:00Z</originalAirDate>
      <vProducer/>
      <series>
        <isEpisodic>true</isEpisodic>
        <vSeriesGenre>
          <element>Action Adventure</element>
          <element>Drama</element>
          <element>Fantasy</element>
          <element>Drama</element>
          <element>Action Adventure</element>
          <element>Sci-Fi and Fantasy</element>
        </vSeriesGenre>
        <seriesTitle>Smallville</seriesTitle>
      </series>
      <showType value="5">SERIES</showType>
      <title>Smallville</title>
      <vWriter>
        <element>Gough|Alfred</element>
        <element>Millar|Miles</element>
        <element>Levens|Philip</element>
      </vWriter>
    </program>
    <channel>
      <callsign/>
    </channel>
    <tvRating value="4">PG</tvRating>
  </showing>
  <startTime>2014-01-16T13:59:58Z</startTime>
  <stopTime>2014-01-16T14:59:59Z</stopTime>
  <bitstreamFormat>
    <vFormat>
      <element>
        <vByte>
          <base64>EjQAAwABAjoBywxXAAAADwAAAAQAAAACAAAAAwAAAA==</base64>
        </vByte>
      </element>
    </vFormat>
  </bitstreamFormat>
  <expirationTime>2038-01-19T00:00:00Z</expirationTime>
</TvBusMarshalledStruct:TvBusEnvelope>
        },
    },
);

sub get_tivo_xml {
    my $show = shift || die 'missing show';
    my $title = shift || die 'missing title';

    if (exists $tivo_xml{$show}) {
        if (exists $tivo_xml{$show}{$title}) {
            return $tivo_xml{$show}{$title};
        }
        else {
            die "No input found for $show $title";
        }
    }
    else {
        die "No input found for $show";
    }
}

sub get_tvrage_xml {
    my $show = shift || die 'missing show';

    if (exists $tvrage_xml{$show}) {
        return $tvrage_xml{$show};
    }
    else {
        die "No input found for $show";
    }
}

1;

__END__

=head1 PURPOSE

Provide input for test suite.

=head1 SYNOPSIS

use Local::TestInput;

my $tivo_xml = get_tivo_xml($show_title, $episode_title);
my $tvrage_xml = get_tvrage_xml($show_title);

=head1 Author

Jeremy Singletary <jeremys@rickyninja.net>
